# Generated by Django 4.0.5 on 2022-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_rf', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
