# Generated by Django 4.0.5 on 2022-08-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_rf',
            new_name='payment_ref',
        ),
    ]
