# Generated by Django 4.0.5 on 2022-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payment_rf_payment_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
