# Generated by Django 4.0.5 on 2022-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Success'), ('failed', 'Failed')], max_length=200),
        ),
    ]
